stages:
  - build
  - merge
  - deploy
  - prd-deploy

#======================================================
# Initial vuepress build
#======================================================

vuepress-netlify-build:
  stage: build
  image: node:16-buster
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    # this ensure all submodules are initiazlied correctly
    GIT_SUBMODULE_STRATEGY: recursive
  # Lets optimize the node_modules + vuepress cache
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
        - .vuepress/.cache
  # The main script
  script:
    # NPM ci, is a more consistent varient of npm install
    - npm ci
    # Setup dist dir, and setup netlify assets
    - mkdir -p ./.dist
    - cp -ar netlify-dist/* ./.dist/
    # Let do the dev build
    - npm run build
    # Lets add some build info for debugging 
    - echo "$CI_COMMIT_SHORT_SHA - $ENV_KEY" > ./.dist/_buildinfo.txt
    - echo "$CI_COMMIT_SHORT_SHA - $ENV_KEY" > ./.dist/v3/_buildinfo.txt
  artifacts:
    paths:
      - .dist/
    # Package can get abit too big, 
    # so lets quickly discard it if possible
    expire_in: 24 hour

#======================================================
# Netlify deployments
#======================================================

# Netlify deploy to our "dev" environment
stg-deploy:
  extends: .netlify-dist-prod-deploy
  variables:
    NETLIFY_SITE_KEY: "${NETLIFY_DEV_SITEID}"
  dependencies:
    - vuepress-netlify-build
  only:
    - main

#======================================================
# Netlify deployment templates
#======================================================

# Gitlab MATRIX does not work reliably with multistage pipeline
# Despites what said here : https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82734/diffs 
.netlify-dist-preview-deploy:
  stage: deploy
  image: uilicious/netlify-cli:8
  variables:
    # Disable the git submodule, as its not needed
    GIT_SUBMODULE_STRATEGY: none
  script:
    # for some reason the latest versions of netlify cannot be installed in our gitlab CI/CD runners reliably
    - cd .dist && netlify deploy --dir=. --functions=./netlify/functions --auth "$NETLIFY_DEVOPS_DEPLOY_KEY" --site "$NETLIFY_SITE_KEY"

# Gitlab MATRIX does not work reliably with multistage pipeline
# Despites what said here : https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82734/diffs 
.netlify-dist-prod-deploy:
  stage: deploy
  image: uilicious/netlify-cli:8
  variables:
    # Disable the git submodule, as its not needed
    GIT_SUBMODULE_STRATEGY: none
  script:
    # for some reason the latest versions of netlify cannot be installed in our gitlab CI/CD runners reliably
    - cd .dist && netlify deploy --dir=. --functions=./netlify/functions --auth "$NETLIFY_DEVOPS_DEPLOY_KEY" --site "$NETLIFY_SITE_KEY" --prod

