#=============================================================================
#
#  Clarification notes for netlify.toml
#
#  - this was vallidated only for netlify-cli@8.19.3 / node16
#  - rules are evaluated in sequence until "redirected"
#    - meaning for headers, last rule wins as it can overwrite previous rules
#    - for redirects, first rule wins, as this terminates evaluation
#    - _headers and _redirects file occurs before this netlify.toml
#
#=============================================================================

#-------------------------------------------------------------
#
# Microcaching for all assets by default
#
# In general, we make the asssumption here that the files
# should have be a short term, or micro cache, for HTML files.
#
# This allow file changes to be updated quickly (in seconds)
# Cache settings to achieve this is as below ...
#
# **public**
# Indicate that the content is publically cachable,
# without this all other cache settings is invalid.
#
# **s-maxage=15**
# Server side, or CDN level caching, of 15 seconds,
# before revalidating
#
# **max-age=15**
# Browser side caching of 15 second, not really
# needed but for CDN who does not support s-maxage,
# this is used instead.
#
# **max-stale=15, stale-while-revalidate=15**
# 15 seconds timespan after the initial max-age second.
# Where "stale" content would still be served
# while being asyncronously updated in the background.
#
# This should be enough for round trip connection
# of CDN cache to the other side of the world
# (your server). With some hiccups along the way.
#
#-------------------------------------------------------------
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, s-maxage=15, max-age=15, max-stale=15, stale-while-revalidate=15"
	ui-cache-mode = "micro"

#-------------------------------------------------------------
# Favicon caching
#-------------------------------------------------------------

[[headers]]
  for = "/favicon.png"
  [headers.values]
    Cache-Control = "public, s-maxage=60, max-age=60, max-stale=60, stale-while-revalidate=60"
	ui-cache-mode = "minute"

#-------------------------------------------------------------
# Aggressive cache
#-------------------------------------------------------------

[[headers]]
  for = "/assets/*"
  [headers.values]
	#-------------------------------------------------------------
	#
	# We will add the cache headers in seconds, for easy refrence
	# Common time period to seconds conversion is as followed
	#
	# One minute: 60
	# One hour:   3600
	# One day:    86400
	# One week:   604800
	# One month:  2628000
	# One year:   31536000
	#
	#-------------------------------------------------------------
    Cache-Control = "public, s-maxage=3600, max-age=3600, max-stale=3600, stale-while-revalidate=3600"
	ui-cache-mode = "hour"
