#=============================================================================
#
#  Clarification notes for netlify.toml
#
#  - this was vallidated only for netlify-cli@8.19.3 / node16
#  - rules are evaluated in sequence until "redirected"
#    - meaning for headers, last rule wins as it can overwrite previous rules
#    - for redirects, first rule wins, as this terminates evaluation
#    - _headers and _redirects file occurs before this netlify.toml
#
#=============================================================================

#-------------------------------------------------------------
#
# Microcaching for all assets by default
#
# In general, we make the asssumption here that the files
# should have be a short term, or micro cache, for HTML files.
#
# This allow file changes to be updated quickly (in seconds)
# Cache settings to achieve this is as below ...
#
# **public**
# Indicate that the content is publically cachable,
# without this all other cache settings is invalid.
#
# **s-maxage=15**
# Server side, or CDN level caching, of 15 seconds,
# before revalidating
#
# **max-age=15**
# Browser side caching of 15 second, not really
# needed but for CDN who does not support s-maxage,
# this is used instead.
#
# **max-stale=15, stale-while-revalidate=15**
# 15 seconds timespan after the initial max-age second.
# Where "stale" content would still be served
# while being asyncronously updated in the background.
#
# This should be enough for round trip connection
# of CDN cache to the other side of the world
# (your server). With some hiccups along the way.
#
#-------------------------------------------------------------
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, s-maxage=15, max-age=15, max-stale=15, stale-while-revalidate=15"
	ui-cache-mode = "micro"

#-------------------------------------------------------------
# Favicon caching
#-------------------------------------------------------------

[[headers]]
  for = "/test/:visibility/favicon.png"
  [headers.values]
    Cache-Control = "public, s-maxage=60, max-age=60, max-stale=60, stale-while-revalidate=60"
	ui-cache-mode = "minute"

[[headers]]
  for = "/favicon.png"
  [headers.values]
    Cache-Control = "public, s-maxage=60, max-age=60, max-stale=60, stale-while-revalidate=60"
	ui-cache-mode = "minute"

#-------------------------------------------------------------
#
#  Very extreamly heavy cache & rewrite for hashed assets
#
#  This was modified to use an unsupported feature listed here
#  https://answers.netlify.com/t/format-of-custom-headers-glob/13037/6
#
#  This may break in future, if so - fallback to micro cache
#
#  [0-9A-Za-z] -> is remapped to ->
#  (0|1|2|3|4|5|6|7|8|9|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)
#
# Does the following regex rule match.
#
# /assets/                                        : Must start with the assets folder
# .+                                              : Match against file name (assumingly)
# \.                                              : Match the dot after the filename
# [0-9A-Za-z][0-9A-Za-z][0-9A-Za-z][0-9A-Za-z]+   : Match against file hash, must have
#                                                   atleast 4 characters. this is done
#                                                   as nginx does not support {4,}
#                                                   curly braces format
# \.([0-9A-Za-z][0-9A-Za-z]+)                     : Match against any filetype {2,}
#
# Examples of matches
# + /assets/studio.0this1is2a3hash4.css
# + /assets/studio.0this1is2a3hash4.css.gz
# + /assets/studio.0this1is2a3hash4.css.map
#
# Examples of failed matches
# - /assets/studio.css
# - /assets/studio.css.map
#
#-------------------------------------------------------------
[[headers]]
  for = "/assets/*.(0|1|2|3|4|5|6|7|8|9|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)(0|1|2|3|4|5|6|7|8|9|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)(0|1|2|3|4|5|6|7|8|9|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)(0|1|2|3|4|5|6|7|8|9|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z)*.*"
  [headers.values]
	#-------------------------------------------------------------
	#
	# We will add the cache headers in seconds, for easy refrence
	# Common time period to seconds conversion is as followed
	#
	# One minute: 60
	# One hour:   3600
	# One day:    86400
	# One week:   604800
	# One month:  2628000
	# One year:   31536000
	#
	#-------------------------------------------------------------
	#
	# As we have detected what looks like a hashing mechanism,
	# between a filename and type. We would perform an extermly
	# agressive file caching here.
	#
	# **public**
	# Indicate that the content is publically cachable,
	# without this all other cache settings is invalid.
	#
	# **s-maxage=2628000**
	# Serverside / CDN level caching, this is intentionally
	# on a "monthly" level, as it will force the CDN to revalidate
	# and delete any outdated CDN files earlier rather then later
	# (and save us on the storage cost)
	#
	# This is configured to be 1 month, before revalidating
	#
	# **max-age=2628000**
	# max-age cache, this configures the browser to cache
	# for up to 1 month, before revalidating. As we do build
	# hashing, frankly this could be unlimited.
	#
	# **max-stale=30, stale-while-revalidate=30**
	# 30 seconds timespan after the above maxage seconds.
	# Where "stale" content would still be served
	# while being asyncronously updated in the background.
	#
	# This should be more then enough for round trip
	# connection of CDN cache to the other side of the
	# world (your server). With some hiccups along the way.
	# (as 5 seconds is more then enough already)
	#
	# Finally "always" should NEVER be configured here,
	# due to the aggressive nature of this cache. As such, this
	# would by default only work on 20X, and 30X respond codes.
	#
	#-------------------------------------------------------------
    Cache-Control = "public, s-maxage=2628000, max-age=2628000, max-stale=30, stale-while-revalidate=30"
	ui-cache-mode = "month"
